### ISSUE TITLE
Reprodução do Exemplo

### ISSUE THREAD

**Issue by opardal** [rafpyprog/sgs#2]
Ola @rafpyprog ,

Tentei reproduzir o seu primeiro exemplo.

from sgs import SGS
sgs = SGS()
df = sgs.get_valores_series(12, '01/01/2016', '31/12/2016')

Quando executei a terceira linha recebi o seguinte erro:

Traceback (most recent call last):

  File "<ipython-input-164-08990e809f73>", line 1, in <module>
    df = sgs.get_valores_series(12, '01/01/2016', '31/12/2016')

  File "c:\python35\lib\site-packages\sgs\sgs.py", line 83, in get_valores_series
    raise ValueError(msg)

ValueError: Valores não encontrados. Verifique o código da série e a data de vigência.

Fui verificar a resposta do request e isso foi o que encontrei:

b'<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Server.userException</faultcode><faultstring>br.gov.bcb.pec.sgs.comum.excecoes.SGSNegocioException: Value(s) not found</faultstring><detail/></soapenv:Fault></soapenv:Body></soapenv:Envelope>'

Você sabe o que pode estar acontecendo?

Obrigado

**Comment by rafpyprog** [comment]
A versão mais recente do pacote agora corrige este erro.
