### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by higorsilva1985** [rafpyprog/sgs#23]
Boa tarde, parabéns pelo trabalho.

Tentei reproduzir o exemplo e imprimir uma série do cdi mas está aparecendo o seguinte erro:

  File "...\Python\Python37\lib\site-packages\sgs\ts.py", line 42, in time_serie
    index.append(to_datetime(i["data"], "pt"))
  File "...\Python\Python37\lib\site-packages\sgs\common.py", line 18, in to_datetime
    locale.setlocale(locale.LC_TIME, locales[language])
  File "...\Python\Python37\lib\locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Você pode ajudar???

**Comment by marcelo-ventura** [comment]
Caro @higorsilva1985 acredito que esse problema seja do seu sistema operacional.
Talvez esse link possa ajudar: https://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting
