### ISSUE TITLE
Unsupported locale

### ISSUE THREAD

**Issue by PedroDaumas** [rafpyprog/sgs#26]
Boa Tarde, quando tento rodar o codigo informado no README do projeto recebo o seguinte erro.

```
import sgs

CDI_CODE = 12
ts = sgs.time_serie(CDI_CODE, start='02/01/2018', end='31/12/2018')
```

Erro:

`"locale.Error: unsupported locale setting"`

**Comment by rafpyprog** [comment]
Olá,

Qual sistema operacional e qual a versão do SGS que você está utilizando?

Em ter, 8 de out de 2019 16:07, Pedro Luís Daumas <notifications@github.com>
escreveu:

**Comment by PedroDaumas** [comment]
Windows 10, nao consegui ver isso no momento, mais acredito ser a mais recente pois dei pip install hoje. Amanha de manha confirmo para voce e atualizo essa resposta

**Versao do sgs: sgs==2.0.3**

**Comment by PedroDaumas** [comment]
Tambem gostaria de informar um outro problema que estou tendo, neste caso com a pesquisa por texto.

Quando utilizo o texto 'divida liquida do setor publico' recebo 50 items atraves do pacote no python, se executo essa mesma busca no site do banco central recebo 213 items. Ao analisar os elementos recebidos me parece que o pacote coleta apenas os dados da 1 pagina da busca no sgs deixado de lado as outras paginas.

**Comment by royopa** [comment]
@rafpyprog Problema com locale no Windows corrigido, segue PR
https://github.com/rafpyprog/pySGS/pull/27

**Comment by rafpyprog** [comment]
Muito obrigado @royopa . Pacote atualizado para a versão 2.0.4 com o fix para Windows.
