### ISSUE TITLE
Coletar mais informações.

### ISSUE THREAD

**Issue by JnsFerreira** [rafpyprog/sgs#3]
Existe algum modo de coletar por exemplo, o título da série, periodicidade, unidade de medida, etc?

**Comment by rafpyprog** [comment]
Vou acrescentar esta funcionalidade na versão 2.0 que deverá sair nas próximas semanas.

**Comment by rafpyprog** [comment]
Os metadados agora podem ser acessados na versão 2.0 do pacote utilizando a função ```sgs.metadata```. Documentação: https://pysgs.readthedocs.io/en/latest/quickstart.html#metadata

**Comment by JnsFerreira** [comment]
Rafael,

Muito obrigado pela implementação!

Parabéns pelo ótimo trabalho, sem dúvida será muito utilizada!
